#####################################################################
# A Mainnet https://github.com/flashbots/builder Configuration File #
#####################################################################

[Eth]
NetworkId = 1
SyncMode = "full"
NoPruning = false
NoPrefetch = false
LightPeers = 100
DatabaseCache = 768
TrieCleanCache = 256
TrieDirtyCache = 256
DatabaseFreezer = ""
TrieTimeout = 3600000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

# [Builder]
# Enabled = true # (default: false)
# EnableValidatorChecks = false # (default: false)
# EnableLocalRelay = false # (default: false)
# DisableBundleFetcher = false # (default: false)
# DryRun = false # (default: false)
# RelaySecretKey = "" # (no default)
# ListenAddr = ":28545" # (default: ":28545") 
# GenesisForkVersion = "0x00000000" # (default: "0x00000000")
# BellatrixForkVersion = "0x02000000" # (default: "0x02000000")
# GenesisValidatorsRoot = "0x0000000000000000000000000000000000000000000000000000000000000000" # (default: "0x0000000000000000000000000000000000000000000000000000000000000000")
# BeaconEndpoint = "http://0.0.0.0:5052" # (default: "http://127.0.0.1:5052")
# RemoteRelayEndpoint = "" # (no default)
# BlockValidationBlacklistSourceFilePath = "" # (no-default)
 
[Eth.Ethash]
CacheDir = "ethash"
CachesInMem = 2
CachesOnDisk = 3
DatasetDir = "/builder/.ethash"
DatasetsInMem = 1
DatasetsOnDisk = 2
PowMode = 0

[Eth.TxPool]
Locals = []
NoLocals = false

[Node]
DataDir = "/builder/data"
JWTSecret = "/builder/consensus/prysm/jwt.hex"
# omitempty = ""
IPCPath = "geth.ipc"
HTTPPort = 8545
HTTPVirtualHosts = [ "0.0.0.0" ]
HTTPModules = ["net", "txpool", "debug", "admin", "engine", "web3", "eth", "shh"]
WSPort = 8546
WSModules = ["net", "web3", "eth", "shh"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
StaticNodes = []
TrustedNodes = []

